apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmsingle-ingress
  namespace: vm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: vmsingle.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vmsingle-overwatch
            port:
              number: 8429
