apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmks-overwatch
  namespace: vm
spec:
  configMaps: []
  datasource:
    url: http://vmsingle-vmks.vm.svc.cluster.local.:8429/prometheus
  evaluationInterval: 20s
  externalLabels: {}
  extraArgs:
    external.alert.source: explore?left={"datasource":"VictoriaMetrics","queries":[{"expr":{{
      .Expr|jsonEscape|queryEscape }},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli
      }}","to":"now"}}
    external.url: http://grafana.127.0.0.1.nip.io
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    tag: v1.130.0
  license: {}
  notifiers:
  - url: http://vmalertmanager-vmks-0.vmalertmanager-vmks.vm.svc.cluster.local.:9093
  port: "8080"
  remoteWrite:
    url: http://vmsingle-overwatch.vm.svc.cluster.local.:8429/prometheus/api/v1/write
  selectAllByDefault: true
