kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmstorage-cpu-usage
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmstorage
  mode: all
  stressors:
    cpu:
      load: 100
      workers: 16
  duration: 10m
