kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vmselect-io-usage
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: all
  stressors:
    cpu:
      load: 1
      options:
        - '--io=16'
        - '--agressive'
      workers: 16
  duration: 10m
