kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmagent-to-vminsert-packet-delay
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmagent
  target:
    selector:
      namespaces:
        - vm
      labelSelectors:
        app.kubernetes.io/name: vminsert
    mode: all
  mode: all
  action: delay
  duration: 7m
  delay:
    latency: 30s
    correlation: '0'
    jitter: 5s
  direction: to
