kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vminsert-to-vmstorage-packet-loss
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: all
  action: loss
  duration: 5m
  loss:
    loss: '100'
    correlation: '0'
  direction: to
  target:
    selector:
      namespaces:
        - vm
      labelSelectors:
        app.kubernetes.io/name: vmstorage
    mode: all
