kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vmselect-to-vmstorage-packet-corrupt
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: all
  action: corrupt
  duration: 5m
  corrupt:
    corrupt: '25'
    correlation: '0'
  direction: to
  target:
    selector:
      namespaces:
        - vm
      labelSelectors:
        app.kubernetes.io/name: vmstorage
    mode: all
