kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmstorage-from-vminsert-packet-loss
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmstorage
  mode: all
  action: loss
  duration: 7m
  loss:
    loss: '100'
    correlation: '0'
  direction: from
  target:
    selector:
      namespaces:
        - vm
      labelSelectors:
        app.kubernetes.io/name: vminsert
    mode: all
