kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vminsert-request-delay-75pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: random-max-percent
  value: '75'
  target: Request
  delay: 60s
  port: 8480
  path: '/insert*'
  duration: 5m
