kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vminsert-request-abort
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: all
  target: Request
  abort: true
  port: 8480
  path: /insert*
  duration: 7m
