kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vminsert-response-abort-50pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: fixed-percent
  value: '50'
  target: Response
  abort: true
  port: 8480
  path: /insert*
  duration: 7m
