kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vminsert-response-status-code-50pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: fixed-percent
  value: '50'
  target: Response
  port: 8480
  replace:
    code: 418
  path: '/insert*'
  duration: 5m
