kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vminsert-response-delay-75pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: fixed-percent
  value: '50'
  target: Response
  delay: 75s
  port: 8480
  path: '/insert*'
  duration: 5m
