kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vminsert-request-abort-75pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: random-max-percent
  value: '75'
  target: Request
  abort: true
  port: 8480
  path: /insert*
  duration: 5m
