kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vminsert-response-status-code-75pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vminsert
  mode: random-max-percent
  value: '75'
  target: Response
  port: 8480
  replace:
    code: 418
  path: '/insert*'
  duration: 5m
