kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmselect-response-status-code-50pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: fixed-percent
  value: '50'
  target: Response
  port: 8481
  replace:
    code: 418
  path: '/select*'
  duration: 5m
