kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmselect-response-delay-50pct
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: fixed-percent
  value: '50'
  target: Response
  delay: 5s
  port: 8481
  path: /select/*
  duration: 7m
