kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vm
  name: vmselect-response-abort
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: all
  target: Response
  abort: true
  port: 8481
  path: /select/*
  duration: 5m
