apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: custom-alert-rules
  namespace: monitoring
spec:
  groups:
  - name: custom-rules
    rules:
    - alert: CustomTooHighSlowInsertsRate
      expr: (sum(rate(vm_slow_row_inserts_total[5m])) by(namespace) / sum(rate(vm_rows_inserted_total[5m])) by(namespace)) > 0.5
      for: 1m
      labels:
        severity: warning
    - alert: CustomCPUThrottlingHigh
      expr: |-
        sum(increase(container_cpu_cfs_throttled_periods_total[5m])) by (namespace)
          /
        sum(increase(container_cpu_cfs_periods_total[5m])) by (namespace)
          > ( 30 / 100 )
      for: 1m
      labels:
        severity: warning
