apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmgather-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: vmgather.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmgather
                port:
                  number: 8080
