kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmselect-memory-usage
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmselect
  mode: all
  stressors:
    memory:
      size: 800Mb
      workers: 128
  duration: 7m
