kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmstorage-memory-usage
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmstorage
  mode: all
  stressors:
    memory:
      size: 1024MB
      workers: 128
  duration: 7m
