kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vmstorage-pod-failure
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vmstorage
  mode: all
  action: pod-failure
  duration: 7m
